name: Test
on:
  - push
  - pull_request
jobs:
  unit:
    name: "Unit: ${{ matrix.name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Ruby 3.2 & Rails 7"
            ruby-version: "3.2"
            rails-version: "7"
          - name: "Ruby 3.1 & Rails 7"
            ruby-version: "3.1"
            rails-version: "7"
          - name: "Ruby 3.0 & Rails 7"
            ruby-version: "3.0"
            rails-version: "7"
          - name: "Ruby 2.7 & Rails 7"
            ruby-version: "2.7"
            rails-version: "7"
          - name: "Ruby 3.0 & Rails 6"
            ruby-version: "3.0"
            rails-version: "6"
          - name: "Ruby 2.7 & Rails 6"
            ruby-version: "2.7"
            rails-version: "6"
          - name: "Ruby 2.6 & Rails 6"
            ruby-version: "2.6"
            rails-version: "6"
          - name: "Ruby 2.5 & Rails 6"
            ruby-version: "2.5"
            rails-version: "6"
          - name: "Ruby 2.7 & Rails 6.0"
            ruby-version: "2.7"
            rails-version: "6.0"
          - name: "Ruby 2.6 & Rails 6.0"
            ruby-version: "2.6"
            rails-version: "6.0"
          - name: "Ruby 2.5 & Rails 6.0"
            ruby-version: "2.5"
            rails-version: "6.0"
          - name: "Ruby 2.7 & Rails 5"
            ruby-version: "2.7"
            rails-version: "5"
          - name: "Ruby 2.6 & Rails 5"
            ruby-version: "2.6"
            rails-version: "5"
          - name: "Ruby 2.5 & Rails 5"
            ruby-version: "2.5"
            rails-version: "5"
          - name: "Ruby 2.7 & Rails 5.1"
            ruby-version: "2.7"
            rails-version: "5.1"
          - name: "Ruby 2.6 & Rails 5.1"
            ruby-version: "2.6"
            rails-version: "5.1"
          - name: "Ruby 2.5 & Rails 5.1"
            ruby-version: "2.5"
            rails-version: "5.1"
          - name: "Ruby 2.7 & Rails 5.0"
            ruby-version: "2.7"
            rails-version: "5.0"
          - name: "Ruby 2.6 & Rails 5.0"
            ruby-version: "2.6"
            rails-version: "5.0"
          - name: "Ruby 2.5 & Rails 5.0"
            ruby-version: "2.5"
            rails-version: "5.0"
          - name: "Ruby 2.4 & Rails 4.2"
            ruby-version: "2.4"
            rails-version: "4.2"
            bundler_version: 1
          - name: "Ruby 2.3 & Rails 4.1"
            ruby-version: "2.3"
            rails-version: "4.1"
            bundler_version: 1
    env:
      BUNDLE_GEMFILE: gemfiles/rails${{ matrix.rails-version }}.gemfile
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: ${{ (matrix.ruby_version < '2.6' && 'default') || 'latest' }}
          bundler: ${{ matrix.bundler_version }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test

  app:
    name: "App: Rails ${{ matrix.rails-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: "2.7"
            rails-version: "7"
          - ruby-version: "2.7"
            rails-version: "6"
          - ruby-version: "2.7"
            rails-version: "6.0"
          - ruby-version: "2.7"
            rails-version: "5"
          - ruby-version: "2.7"
            rails-version: "5.1"
          - ruby-version: "2.7"
            rails-version: "5.0"
          - ruby-version: "2.4"
            rails-version: "4.2"
          - ruby-version: "2.3"
            rails-version: "4.1"
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          docker-compose run --rm ruby-${{ matrix.ruby-version }}-rails-${{ matrix.rails-version }}
